# Generated by Django 3.2 on 2022-09-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220917_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
